### ISSUE TITLE
If its Aberdeen's Design & Digital Agency History...

### ISSUE THREAD

**Issue by sunscreem** [caleuanhopkins/ADAH#1]
.., how come the repo isn't ADDAH?

**Comment by caleuanhopkins** [comment]
Too long and some agencies are "design" or "digital" or both so it was to include them all.

-1 karma point for being a smart arse!

**Comment by sunscreem** [comment]
https://en.wikipedia.org/wiki/List_of_minor_biblical_figures,_A%E2%80%93K#Adah

**Comment by sunscreem** [comment]
;)
